data:
  path: input/bike-sharing/
  train: train.csv
  test: test.csv
  target: count
  del_features:
  - casual
  - datetime
  - registered
  submission: sampleSubmission.csv

model:
  name: windspeed-xgboost.model
  path: res/models/
  params:
    max_depth: 5
    eta: 0.1
    gamma: 0
    min_child_weight: 1
    subsample: 1
    colsample_bytree: 1
    objective: reg:squarederror
    eval_metric: rmse
    seed: 42
  verbose_eval: 100
  early_stopping_rounds: 100
  num_boost_round: 10000

output:
  path: output/
  submission: windspeed-xgboost.csv